# -*- coding: utf-8 -*-
"""Task2_Netflix&TV_Shows.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PgVbT1wjqPr43nNbwUGvfpnF55oAFLn
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df=pd.read_csv('netflix_titles.csv')
df.head()

df.info()
df.describe(include='all')

df.isnull().sum()

#Handling missing values

df['country'].fillna('Unknown',inplace=True)
df['rating'].fillna('Not Rated',inplace=True)
df['date_added'].fillna('Unknown',inplace=True)

#Converting date column
df['date_added']=pd.to_datetime(df['date_added'],errors='coerce')

#Exploratory Data Analysis (EDA)
sns.countplot(x='type',data=df)
plt.title('Movies vs TV Shows on Netflix')
plt.show()

#Content added over Years
df['year_added']=df['date_added'].dt.year

sns.countplot(x='year_added',data=df)
plt.xticks(rotation=90)
plt.title("Content added over years")
plt.show()

#Top 10 Countries
top_countries=df['country'].value_counts().head(10)

plt.figure(figsize=(8,5))
top_countries.plot(kind='bar')
plt.title("Top 10 content producing countries")
plt.ylabel('Count')
plt.show()

#Rating Distribution
sns.countplot(y='rating',data=df)
plt.title('Rating Distribution on Netflix')
plt.show()